# Generated by Django 5.1.5 on 2025-03-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_cadastro_professores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplinas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=8)),
                ('nome', models.CharField(max_length=255)),
                ('semestre', models.IntegerField()),
                ('carga_horaria', models.IntegerField()),
                ('curso', models.CharField(max_length=255)),
            ],
        ),
    ]
