# Generated by Django 5.1.5 on 2025-03-18 18:02

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_disciplinas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=8)),
                ('nome', models.CharField(max_length=255)),
                ('tipo_curso', models.CharField(choices=[('cai', 'CAI'), ('tec', 'TEC'), ('fic', 'FIC')], default='tec', max_length=10)),
                ('minu_aula', models.IntegerField(validators=[django.core.validators.MaxValueValidator(60)])),
            ],
        ),
        migrations.AlterField(
            model_name='professores',
            name='ni',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.CreateModel(
            name='Ambientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sala', models.CharField(max_length=8)),
                ('capacidade', models.IntegerField(validators=[django.core.validators.MaxValueValidator(140)])),
                ('lin_atend', models.CharField(max_length=255)),
                ('periodo', models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite')], default='manha', help_text='Escolha o período da turma: Manhã, Tarde ou Noite.', max_length=5)),
                ('prof_resp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.professores')),
            ],
        ),
    ]
