# Generated by Django 5.1.5 on 2025-03-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_ambientes_curso_ambientes_fim_ambientes_inicio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Turmas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_turma', models.CharField(max_length=8)),
                ('turma', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='ambientes',
            name='periodo',
            field=models.CharField(choices=[('manha', 'Manhã'), ('tarde', 'Tarde'), ('noite', 'Noite'), ('sabado', 'Sábado')], default='manha', help_text='Escolha o período da turma: Manhã, Tarde ou Noite.', max_length=6),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='tipo_curso',
            field=models.CharField(choices=[('cai', 'CAI'), ('ct', 'CT'), ('fic', 'FIC'), ('cs', 'CS')], default='ct', max_length=10),
        ),
    ]
