# Generated by Django 5.1.5 on 2025-03-31 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_cursos_minu_aula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='minu_aula',
            field=models.IntegerField(),
        ),
    ]
